apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: aei5jqclh-python 
  janus-idp.io/tekton: aei5jqclh-python
  backstage.io/kubernetes-id: aei5jqclh-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: aei5jqclh-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  